# Generated by Django 5.2.9 on 2025-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needycase',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='needycase',
            old_name='story',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='needycase',
            old_name='user',
            new_name='needy',
        ),
        migrations.AlterField(
            model_name='needycase',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
